twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['form/layout.html.twig']

    paths:
        '%kernel.project_dir%/public/css/': styles

when@test:
    twig:
        strict_variables: true
