vich_uploader:
    db_driver: orm

    mappings:
        project_images:
            uri_prefix: '%APP_PATH_IMAGE_UPLOAD%'
            upload_destination: '%kernel.project_dir%/public/%APP_PATH_IMAGE_UPLOAD%'