vich_uploader:
    db_driver: orm

    mappings:
        project_images:
            uri_prefix: '%APP_PATH_IMAGE_UPLOAD%/projects'
            upload_destination: '%kernel.project_dir%/public/%APP_PATH_IMAGE_UPLOAD%/projects'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_update: true